name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint-and-typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm install

      - name: Check Formatting
        run: npx prettier --check .

      - name: Lint and Auto-Fix
        run: npm run lint -- --fix

      - name: Typecheck
        run: npx tsc --noEmit

      - name: Test
        run: npm test
